config/routes.rb
Rails.application.routes.draw do

  devise_for :users,  :controllers => { :users => 'users' }
  devise_for :models
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'bees#index'

  resources :posts
  resources :flavors
  resources :bees
  resources :admin_users
  resources :leads
  resources :faqs, only: %i[index]
  resources :job_applicants, only: %i[new create]
  resources :trailers, only: %i[new create]

  namespace :admin do
    resources :google_reviews do
      post :upsert_reviews, on: :collection
    end
  end

  get 'about' => 'bees#about'
  put 'subscribe', to: 'subscribe#create'
  get 'event' => 'bees#event'
  get 'cards' => 'bees#cards'
  get 'merch' => 'bees#merch'
  get 'cakes' => 'bees#cakes'
  get 'order' => 'bees#order'
  

end

app/models/flavor.rb
class Flavor < ApplicationRecord
  belongs_to :bee, optional: true
  mount_uploader :image, ImageUploader

  def self.descriptions
    pluck(:description).flatten.join(' ')
  end

  def self.names
    pluck(:name).flatten.join(' ')
  end

  def self.images
    pluck(:image).flatten.join(' ')
  end

  def self.search(search)
    if search
      self.where("title LIKE ? OR body LIKE ?", "%#{search}%", "%#{search}%")
    else
      self.all
    end
  end
end

app/controllers/flavors_controller.rb
class FlavorsController < ApplicationController
  before_action :set_flavor, only: [:show, :edit, :update, :destroy]

  # GET /flavors
  # GET /flavors.json
  def index
    @flavors = Flavor.where(instock:["Yes"]).order('name ASC')
    @outstock = Flavor.where(instock:["No"]).order('name ASC')
    set_meta_tags title: "Flavors",
              site: "B's Ice Cream",
              reverse: true,
              description: "Check out our unique homemade flavors made right in our shop",
              keywords: "best ice cream, homemade ice cream, ice cream, ice cream near me, south shore ice cream, ice cream places near me, ice cream shop, ice cream shops near me, best ice cream near me, ice cream nearby, homemade ice cream near me, ice cream parlour, ice cream stores near me, ice cream parlour near me, creamery near me, the ice cream shop, ice cream around me, nearest ice cream shop, homemade vanilla ice cream, nearest ice cream place, good ice cream near me, closest ice cream, cream ice cream, places to get ice cream near me, ice cream company, best ice cream places near me" 
  end

  # GET /flavors/1
  # GET /flavors/1.json
  def show
  end

  # GET /flavors/new
  def new
    @flavor = Flavor.new
  end

  # GET /flavors/1/edit
  def edit
  end

  # POST /flavors
  # POST /flavors.json
  def create
    @flavor = Flavor.new(flavor_params)

    respond_to do |format|
      if @flavor.save
        format.html { redirect_to @flavor, notice: 'Flavor was successfully created.' }
        format.json { render :show, status: :created, location: @flavor }
      else
        format.html { render :new }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flavors/1
  # PATCH/PUT /flavors/1.json
  def update
    respond_to do |format|
      if @flavor.update(flavor_params)
        format.html { redirect_to @flavor, notice: 'Flavor was successfully updated.' }
        format.json { render :show, status: :ok, location: @flavor }
      else
        format.html { render :edit }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flavors/1
  # DELETE /flavors/1.json
  def destroy
    @flavor.destroy
    respond_to do |format|
      format.html { redirect_to flavors_url, notice: 'Flavor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flavor
      @flavor = Flavor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flavor_params
      params.require(:flavor).permit(:name, :description, :availability, :flavorofweek, :image, :created_at, :instock)
    end
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/views/flavors/_form.html.erb
<%= form_for(@flavor) do |f| %>
  <% if @flavor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flavor.errors.count, "error") %> prohibited this flavor from being saved:</h2>

      <ul>
      <% @flavor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
    <div class="field">
    <%= f.label :availability %><br>
    <%= f.text_area :availability %>
  </div>
    <div class="field">
    <%= f.label :flavorofweek %><br>
    <%= f.text_area :flavorofweek %>
  </div>
    <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flavors/edit.html.erb
<h1>Editing Flavor</h1>

<%= render 'form' %>

<%= link_to 'Show', @flavor %> |
<%= link_to 'Back', flavors_path %>

app/views/flavors/index.html.erb
<section class="dzsparallaxer auto-init dzsparallaxer---window-height" 
data-responsive-reference-width="1280" 
data-responsive-optimal-height="500"    
style="position: relative; height: 500px;" 
data-options='{  mode_scroll: "normal" }'>
  <div class="divimage dzsparallaxer--target " data-src="<%= image_path('flavor2.jpg')%>" style="width: 100%; height: 100%; background-image: url(<%= image_path('flavor2.jpg')%>);">
    <div class="content-table">
        <div class="content-middle pt10 ">

            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-lg-8 ml-auto mr-auto text-center">
                                  <h2 class="font400 text-white h1">Homemade Flavors</h2>
                        <p class="lead text-white">
                        </p>
                    </div>
                </div>
            </div>
        </div><!--hero inner-->
    </div>
    <!--parallax hero-->
  </div>
  <!--parallax image div-->
  <div class="mouse-down">
    <a data-scroll href="#flavors">
      <i class="fa-solid fa-angle-down">
      </i>
    </a>
  </div>
</section>

<div class="container pt50 pb10" id="about">
    <div class="row">
        <div class="col-md-12 mr-auto ml-auto text-center mb20">
            <h3 class="h1"> Check out our homemade ice cream flavors made daily</h3>
        </div>
  </div>
</div>        
        
<div class="col-md-8 mr-auto ml-auto text-center mb20">
      <p class="lead">
      We make small batch homemade premium ice cream right in our shop! Our flavors will rotate based on the fresh ingredients available and based on the season. We will always have a non-dairy option. Below is a list of the flavors we have made to date. <strong> Our flavors rotate frequently.</strong> Come on in and try one of our delicious homemade flavors! 
      </p>
</div>


        <!-- products page -->
<div class="container pt50 pb50">
    <div class="row">
        <div class="col-md-6 mb20">
          <h3>
            <em>Homemade flavors in shop today</em>
          </h3>  
        </div>
<!--          <div class="col-md-3 ml-auto mb20 text-right">
             <select class="form-control form-control-sm">
                 <option>Seasonal Items</option>
                 <option>Year Round Items</option>
             </select>
        </div> -->
    </div>
  <!-- start of flavors -->   
    <div class="row">
      <% @flavors.each do |flavor| %>
          <div class="col-md-4 mb40">
              <a class="shop-item-card">
                  <img src="<%= flavor.image %>" alt="" class="img-fluid mb20">
                  <h5 class="font600 h6">
                    <%= flavor.name %>
                      <span class="float-right badge badge-secondary">
                        <%= flavor.availability %>
                      </span>
                  </h5>
                  <p class="lead text-muted"><%= flavor.description %></p>
              </a>
          </div>
      <% end %>
    </div>

    </div>


</div>  

app/views/flavors/new.html.erb
<h1>New Flavor</h1>

<%= render 'form' %>

<%= link_to 'Back', flavors_path %>

app/views/flavors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flavor.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @flavor.description %>
</p>

<%= link_to 'Edit', edit_flavor_path(@flavor) %> |
<%= link_to 'Back', flavors_path %>