config/routes.rb
Rails.application.routes.draw do

  devise_for :users,  :controllers => { :users => 'users' }
  devise_for :models
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'bees#index'

  resources :posts
  resources :flavors
  resources :bees
  resources :admin_users
  resources :leads
  resources :faqs, only: %i[index]
  resources :job_applicants, only: %i[new create]
  resources :trailers, only: %i[new create]

  namespace :admin do
    resources :google_reviews do
      post :upsert_reviews, on: :collection
    end
  end

  get 'about' => 'bees#about'
  put 'subscribe', to: 'subscribe#create'
  get 'event' => 'bees#event'
  get 'cards' => 'bees#cards'
  get 'merch' => 'bees#merch'
  get 'cakes' => 'bees#cakes'
  get 'order' => 'bees#order'
  

end

app/models/trailer.rb
class Trailer < ApplicationRecord
  validates :firstname, :lastname, :detail, :email, :phone, :date, :address1, :city, :state, :zip, :eventstart, :guest, presence: true
  
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }
  validates :guest, numericality: { greater_than: 0, message: "must be a positive number" }
  validates :zip, format: { with: /\A\d{5}(-\d{4})?\z/, message: "should be a valid ZIP code (e.g., 12345 or 12345-6789)" }, allow_blank: true
  
  validate :date_not_in_past
  validate :date_not_too_far_in_future

  after_create_commit :send_emails

  private

  def date_not_in_past
    if date.present? && date < Date.current
      errors.add(:date, "must be on or after today's date")
    end
  end
  
  def date_not_too_far_in_future
    if date.present? && date > Date.current + 2.years
      errors.add(:date, "cannot be more than 2 years in the future")
    end
  end

  def send_emails
    # Send notification email to shop owners
    TrailerMailer.notify_shop(self).deliver_later
    
    # Send acknowledgment email to the customer
    TrailerMailer.acknowledgment(self).deliver_later
  end
end

app/controllers/trailers_controller.rb
class TrailersController < InheritedResources::Base
  include RecaptchaVerifiable

  def new
    @trailer_lead = Trailer.new
  end

  def edit
  end

  def create
    @trailer_lead = Trailer.new(trailer_params)

    respond_to do |format|
      if verify_recaptcha_v3(params[:recaptcha_token], 'trailer_inquiry')
        if @trailer_lead.save 
          format.turbo_stream
          format.html { redirect_to @trailer_lead, notice: 'Thank You. Your inquiry was successfully submitted.' }
          format.json { render :show, status: :created, location: @trailer_lead }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @trailer_lead.errors, status: :unprocessable_entity }
        end
      else
        flash.now[:alert] = "reCAPTCHA verification failed. Please try again."
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: { error: "reCAPTCHA verification failed" }, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @trailer_lead.update(trailer_params)
        format.html { redirect_to @trailer_lead, notice: 'Inquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @trailer_lead }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trailer_lead.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @trailer_lead.destroy
    respond_to do |format|
      format.html { redirect_to trailers_url, notice: 'Inquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def trailer_params
      params.require(:trailer).permit(:firstname, :lastname, :detail, :email, :phone, :date, :address1, :city, :state, :zip, :eventstart, :guest)
    end
end

app/helpers/trailers_helper.rb
module TrailersHelper
end

app/views/trailers/_form.html.erb
<%= form_for(@trailer_lead, html: { id: "trailer-inquiry-form", data: { recaptcha_v3_target: "form" } }) do |f| %>

    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade show mb-4" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <hr class="mb40 mt40">
    <div class="leave-comment">
      <h4 class="mb30 font600 h5">EVENT INQUIRY FORM</h4>
        <form class="comment-form">
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.text_field :firstname, class: "form-control", required: true, placeholder: "First Name", 
                    autocomplete: "given-name", title: "Please enter a valid first name (2-50 letters)" %>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.text_field :lastname, class: "form-control", required: true, placeholder: "Last Name", 
                    autocomplete: "family-name", title: "Please enter a valid last name (2-50 letters)" %>
              </div>
            </div> 
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.email_field :email, class: "form-control", required: true, placeholder: "Email", 
                    autocomplete: "email", inputmode: "email" %>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.telephone_field :phone, class: "form-control", required: true, placeholder: "Phone", 
                    autocomplete: "tel", inputmode: "tel", pattern: "[0-9()+ -]{10,15}", 
                    title: "Please enter a valid phone number (10-15 digits)" %>
              </div>
            </div>                  
            <div class="col-sm-6">
              <div class="form-group">
                 <%= f.label :date, 'Event Date' %>
                <%= f.date_field :date, class: "form-control", placeholder: "Event Date", required: true,
                    min: Date.current.to_s, max: (Date.current + 2.years).to_s %>
              </div>
            </div>                  
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :eventstart, 'Start Serving Time' %>
                <%= f.time_field :eventstart, class: "form-control", required: true, placeholder: "Event Start Time" %>
              </div>
            </div> 
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.text_field :address1, class: "form-control", required: true, placeholder: "Event Address",
                    autocomplete: "address-line1" %>
              </div>
            </div> 
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.number_field :guest, class: "form-control", required: true, placeholder: "Number of guests",
                    min: "1", max: "100000", inputmode: "numeric" %>
              </div>
            </div> 
            <div class="col-sm-4">
              <div class="form-group">
                <%= f.text_field :city, class: "form-control", required: true, placeholder: "Event City",
                    autocomplete: "address-level2" %>
              </div>
            </div> 
            <div class="col-sm-4">
              <div class="form-group">
                <%= f.text_field :state, class: "form-control", required: true, placeholder: "Event State",
                    autocomplete: "address-level1" %>
              </div>
            </div> 
            <div class="col-sm-4">
              <div class="form-group">
                <%= f.text_field :zip, class: "form-control", required: true, placeholder: "Event Zip",
                    autocomplete: "postal-code", pattern: "\\d{5}(-\\d{4})?", 
                    title: "Please enter a valid ZIP code (e.g., 12345 or 12345-6789)", inputmode: "numeric" %>
              </div>
            </div>
            <div class="col-sm-12"> 
              <div class="form-group">
                <%= f.text_area :detail, class: "form-control", required: true, placeholder: "Brief Event Description",
                    rows: "3", maxlength: "5000" %>
              </div>
            </div>

            <%= hidden_field_tag :recaptcha_token, nil, id: "recaptcha-token", data: { recaptcha_v3_target: "token" } %>

            <% if flash[:alert] %>
              <div class="col-sm-12">
                <div class="alert alert-danger alert-dismissible fade show mb-4" role="alert">
                  <%= flash[:alert] %>
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
              </div>
            <% end %>

            <% if @trailer_lead.errors.any? %>
              <div class="col-sm-12">
                <div class="alert alert-danger mb-4" role="alert">
                  <h5><i class="bi bi-exclamation-triangle-fill"></i> Please correct the following errors:</h5>
                  <ul class="mb-0">
                    <% @trailer_lead.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              </div>
            <% end %>

              <div class="actions mt-2">

                  <%= f.submit "Submit", class: "btn btn-dark" %>

            </div>
          </div>  
        </form>
    </div>
  </hr>

<% end %>

app/views/trailers/_success.html.erb
<div class="alert alert-success alert-dismissible fade show mb-4" role="alert">
  <h4 class="alert-heading">Thank You!</h4>
  <p>Your inquiry was successfully submitted. We'll be in touch with you soon.</p>
  <hr>
  <p class="mb-0">Reference ID: <%= trailer.id %></p>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

<div class="text-center mt-4">
  <a href="<%= root_path %>" class="btn btn-primary">Return to Home</a>
</div>

app/views/trailers/_trailer.html.erb
<div id="<%= dom_id trailer %>">
</div>

app/views/trailers/create.turbo_stream.erb
<%= turbo_stream.update "trailer-form" do %>
  <div class="alert alert-success alert-dismissible fade show mb-4" role="alert">
    <h4 class="alert-heading">Thank You!</h4>
    <p>Your inquiry was successfully submitted. We'll be in touch with you soon.</p>
  </div>
<% end %>

app/views/trailers/edit.html.erb
<h1>Editing trailer</h1>

<%= render "form" %>

<br>

<div>
  <%= link_to "Show this trailer", @trailer %> |
  <%= link_to "Back to trailers", trailers_path %>
</div>

app/views/trailers/index.html.erb
<body>
  <!--page title-->
  <div class="dzsparallaxer auto-init height-is-based-on-content "  data-options='{   direction: "reverse"}'
       data-responsive-reference-width="1280" data-responsive-optimal-height="500">
    <div class="divimage dzsparallaxer--target" style="width: 100%; height: 100%; background-image: url(<%= image_path('hero2.jpg')%>)">
    </div>

    <div class="container pt100 pb70">
        <div class="row pb50">
            <div class="col-md-8 ml-auto mr-auto wow bounceIn" data-wow-delay=".2s">
                <h3 class="h1 text-center font500  pt100 text-black"></h3>
            </div>
        </div>
    </div>  
  </div><!--parallax-->
  <!--/.page-title-->
  <%= turbo_frame_tag 'flash-message' %>

  <div class="container contact-form pt100 pb70">
    <%= turbo_frame_tag 'job-applicant-form-wrapper', class: "container contact-form pt50 pb50" do %>
      <div class="text-center">
        <h1>B's Ice Cream Truck</h1>

        <%# Start blog format %>
        <div class="container pt10 pb10">
            <div class="row">
                <div class="col-md-12 mb30">
                   
                        
                        <div class="post-thumbnail">
                            <img src='<%= image_path('trailer_3.jpg')%>' alt="" class="img-fluid" style="width: 70%">
                        </div>

                    <div class="post-full">
                        <div class="blog-meta">
                            <h2>Standard post title</h2>


                        <div class="post-content">
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae ut ratione similique temporibus tempora dicta soluta? Qui hic, voluptatem nemo quo corporis dignissimos voluptatum debitis cumque fugiat mollitia quasi quod. Repudiandae possimus quas odio nisi optio asperiores, vitae error laudantium, ratione odit ipsa obcaecati debitis deleniti minus, illo maiores placeat omnis magnam.
                            </p>
                            <blockquote>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae ut ratione similique temporibus tempora dicta soluta? Qui hic, voluptatem nemo quo corporis dignissimos voluptatum debitis cumque fugiat mollitia quasi quod.<br><em>John Doe</em></blockquote>
                            <br>
                            <h4>In hac habitasse platea dictumst.</h4>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae ut ratione similique temporibus tempora dicta soluta? Qui hic, voluptatem nemo quo corporis dignissimos voluptatum debitis cumque fugiat mollitia quasi quod. Repudiandae possimus quas odio nisi optio asperiores, vitae error laudantium, ratione odit ipsa obcaecati debitis deleniti minus, illo maiores placeat omnis magnam.
                            </p>
                            <h1>To Inquire about truck availablity contact us here.
                            <div class="media mb20">
                                <span class="icon-round-40 float-left mr-3 bg-light"><i class="fa fa-envelope"></i></span>
                                <p class="media-body pt5">
                                <a href="mailto:bsicecreamtruck@gmail.com" class="btn btn-underline text-black">
                                bsicecreamtruck@gmail.com</a></p>
                            </div>


                            <a>
                                <%= link_to "To Inquire about truck availablity contact us here.", new_trailer_path, class: 'media mb20', data: { turbo_frame: '_top' } %>
                            </a>




                            </h1>

                            <ul class="list-inline share">
                                <li class="list-inline-item">Share it:</li>
                                <li class="list-inline-item"><a class="btn btn-underline" href="javascript:void(0)" data-toggle="tooltip" title="" data-original-title="Facebook"><i class="fa fa-facebook"></i> Facebook</a></li>
                                <li class="list-inline-item"><a class="btn btn-underline" href="javascript:void(0)" data-toggle="tooltip" title="" data-original-title="Twitter"><i class="fa fa-twitter"></i> Twitter</a></li>
                                <li class="list-inline-item"><a class="btn btn-underline" href="javascript:void(0)" data-toggle="tooltip" title="" data-original-title="Pinterest"><i class="fa fa-pinterest"></i> Pinterest</a></li>
                                <li class="list-inline-item"><a class="btn btn-underline" href="javascript:void(0)" data-toggle="tooltip" title="" data-original-title="Linkedin"><i class="fa fa-linkedin"></i> Linkedin</a></li>
                            </ul>
                        </div>

                    </div><!--post end-->

            </div>
        </div>
        <%# End blog format %>

      </div>
  </div>



<% @trailer_leads.each do |trailer| %>
<% trailer.firstname %>
<% trailer.lastname %>
<% end %>


<% end %>

</body>

app/views/trailers/new.html.erb
<body>
  <!--page title-->
  <div class="dzsparallaxer auto-init height-is-based-on-content "  data-options='{   direction: "reverse"}'
       data-responsive-reference-width="1280" data-responsive-optimal-height="500">
    <div class="divimage dzsparallaxer--target" style="width: 100%; height: 100%; background-image: url(<%= image_path('hero2.jpg')%>)">
    </div>

    <div class="container pt100 pb70">
        <div class="row pb50">
            <div class="col-md-8 ml-auto mr-auto wow bounceIn" data-wow-delay=".2s">
                <h3 class="h1 text-center font500  pt100 text-black"></h3>
            </div>
        </div>
    </div>  
  </div><!--parallax-->
  <!--/.page-title-->
  <%= turbo_frame_tag 'flash-message' %>

  <div class="container contact-form pt90 pb50">
    <h1 class="text-center"><strong>B's Ice Cream Truck</strong></h1>

    <%# Start blog format %>
    <div class="container pt10 pb10">
      <div class="row">
        <div class="col-md-12 mb30">
          <div class="post-thumbnail text-center">
            <a href="<%= asset_path('trailer_8.jpg') %>" target="_blank" rel="noopener">
                  <img 
                    src='<%= asset_path('trailer_8-800.jpg') %>' 
                    srcset="
                      <%= asset_path('trailer_8-400.jpg') %> 400w,
                      <%= asset_path('trailer_8-800.jpg') %> 800w,
                      <%= asset_path('trailer_8-1200.jpg') %> 1200w
                    "
                    sizes="(max-width: 600px) 400px, (max-width: 900px) 800px, 1200px"
                    alt="Trailer 8" class="img-fluid" style="width: 70%">
            </a>
          </div>
          <div class="post-full">
            <div class="blog-meta">
              <h3 class="text-center">Perfect for your next event</h3>
              <div class="post-content">
                <p class="h5">
                      We service: Weddings, Birthday Parties, Festivals, Coporate Events, Graduations, School Events and more!
                </p>   

                <%# Cups and cones event box         %>
                <div class="bg-white pt90 pb50">
                  <div class="container">
                      <div class="row align-items-center">
                        <div class="col-lg-5 mr-auto ml-auto mb40">
                            <h4 class=" h2 mb40"><strong>Cups & Cones Event</strong></h4>
                            <p class=" text-muted">
                                Includes up to eight different flavors of our homemade ice cream. Hand scooped into cups or sugar cones. Rainbow and chocolate sprinkles are included. 70 people required or meet our minimum fee for service.
                            </p>
                        </div>
                        <div class="col-lg-5 ml-auto mb40">
                          <a href="https://www.dropbox.com/scl/fi/5iz7kaxtizeh6j8imfvb9/trailer_7.jpg?rlkey=3o6jlg1ou3saeuxxxoiy56chj&st=imhqonbk&raw=1" target="_blank" rel="noopener">
                          <img 
                            src='<%= asset_path('trailer_7-800.jpg') %>' 
                            srcset="
                              <%= asset_path('trailer_7-400.jpg') %> 400w,
                              <%= asset_path('trailer_7-800.jpg') %> 800w,
                              <%= asset_path('trailer_7-1200.jpg') %> 1200w
                            "
                            sizes="(max-width: 600px) 400px, (max-width: 900px) 800px, 1200px"
                            alt="Trailer 7" class="img-fluid" style="width: 100%">
                          </a>
                        </div>
                      </div>
                  </div>
                </div>


                <%# Sundae party box %>
                <div class="bg-white pt50 pb50">
                  <div class="container">
                      <div class="row align-items-center">
                          <div class="col-lg-5 ml-auto mb40">
                              <a href="https://www.dropbox.com/scl/fi/bravx0eno9pimy73tt8i7/trailer_6.jpg?rlkey=owmy2oda8cllzcfdvrql1oqin&st=opmue0d0&raw=1" target="_blank" rel="noopener">
                              <img 
                                src='<%= asset_path('trailer_6-800.jpg') %>' 
                                srcset="
                                  <%= asset_path('trailer_6-400.jpg') %> 400w,
                                  <%= asset_path('trailer_6-800.jpg') %> 800w,
                                  <%= asset_path('trailer_6-1200.jpg') %> 1200w
                                "
                                sizes="(max-width: 600px) 400px, (max-width: 900px) 800px, 1200px"
                                alt="Trailer 6" class="img-fluid" style="width: 100%">
                              </a>
                          </div>
                          <div class="col-lg-5 mr-auto ml-auto mb40">
                              <h4 class=" h2 mb40"><strong>Sundae Party</strong></h4>
                              <p class=" text-muted">
                                  Includes up to eight different flavors of our homemade ice cream, hot fudge, caramel, marshmallow, whip cream and cherries. 60 people required or meet our minimum fee for service.
                              </p>
                          </div>
                      </div>
                  </div>
                </div>


                <%# Kids sundae party box %>
                <div class="bg-white pt50 pb50">
                    <div class="container">
                      <div class="row align-items-center">
                        <div class="col-lg-5 mr-auto ml-auto mb40">
                            <h4 class=" h4 mb40"><strong>Make your own Kid Sundae Party</strong></h4>
                            <p class=" text-muted">
                                Perfect for day care, preschool and Montessori schools.   One flavor pre-scooped and ready for the little ones to top on their own. Includes, hot fudge, whip cream, cherries, rainbow sprinkles, chocolate sprinkles, gummy worms & bears, caramel sauce and mini M&M’s. 70 people required, or meet our minimum fee for service.
                            </p>
                        </div>
                        <div class="col-lg-5 ml-auto mb40">
                            <a href="https://www.dropbox.com/scl/fi/f1w4us0z6yugca5hcayk3/trailer_5.jpg?rlkey=9al9d15teh18jkd892n8gbkny&st=aasyqxjw&raw=1" target="_blank" rel="noopener">
                            <img 
                              src='<%= asset_path('trailer_5-800.jpg') %>' 
                              srcset="
                                <%= asset_path('trailer_5-400.jpg') %> 400w,
                                <%= asset_path('trailer_5-800.jpg') %> 800w,
                                <%= asset_path('trailer_5-1200.jpg') %> 1200w
                              "
                              sizes="(max-width: 600px) 400px, (max-width: 900px) 800px, 1200px"
                              alt="Trailer 5" class="img-fluid" style="width: 100%">
                            </a>
                        </div>
                      </div>
                    </div>
                </div>


                <p class="text-muted mb5">
                Meals Tax (7%) will be added to all events. Additional Time/Staffing fee may be required to accommodate larger parties or travel. Deposit of 50% is required to secure your event, fully refundable up to 30 days prior to the event date. Final payment and due one week prior to event date.  
                </p></br>

                <div class="post-content">
                  <p class="h5">
                Would you like B's Ice Cream at your next event?
                Please fill out our inquiry form below or email us at:
                    <a href="mailto:bsicecreamtruck@gmail.com" class="btn btn-underline text-primary">bsicecreamtruck@gmail.com</a>
                  </p>
                </div>       

           
            </div><!--post end-->
          </div>
        </div>
          <%# End blog format %>
      </div>
    </div>
    <%= turbo_frame_tag "trailer-form" do %>
      <div data-controller="recaptcha-v3"
           data-recaptcha-v3-site-key-value="<%= Rails.application.credentials.recaptcha_site_key_v3 %>"
           data-recaptcha-v3-action-value="trailer_inquiry">
        <!-- The Stimulus controller will handle token generation -->
        <%= render 'form', trailer: @trailer_lead %>
      </div>
    <% end %>
    </br>
   </div> 
</body>

app/views/trailers/show.html.erb
<body>
  <div class="dzsparallaxer auto-init height-is-based-on-content "  data-options='{   direction: "reverse"}'
       data-responsive-reference-width="1280" data-responsive-optimal-height="500">
    <div class="divimage dzsparallaxer--target" style="width: 100%; height: 100%; background-image: url(<%= image_path('hero2.jpg')%>)">
    </div>

    <div class="container pt100 pb70">
        <div class="row pb50">
            <div class="col-md-8 ml-auto mr-auto wow bounceIn" data-wow-delay=".2s">
                <h3 class="h1 text-center font500  pt100 text-black"></h3>
            </div>
        </div>
    </div>  
  </div><!--parallax-->

  <div class="container contact-form pt100 pb70">
    <%= turbo_frame_tag 'job-applicant-form-wrapper', class: "container contact-form pt50 pb50" do %>

      <p style="color: green"><%= notice %></p>

      <%= turbo_frame_tag 'flash-message' %>

            <% end %>
  


  <div class="actions mt-2 text-center">
    <%#= link_to 'Edit', edit_trailer_path, class: "btn btn-dark", data: { turbo_frame: '_top' } %> 
    <%= link_to 'Back', new_trailer_path, class: "btn btn-dark", data: { turbo_frame: '_top' } %>
  </div>
</div>
</body>