config/routes.rb
Rails.application.routes.draw do

  devise_for :users,  :controllers => { :users => 'users' }
  devise_for :models
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'bees#index'

  resources :posts
  resources :flavors
  resources :bees
  resources :admin_users
  resources :leads
  resources :faqs, only: %i[index]
  resources :job_applicants, only: %i[new create]
  resources :trailers, only: %i[new create]

  namespace :admin do
    resources :google_reviews do
      post :upsert_reviews, on: :collection
    end
  end

  get 'about' => 'bees#about'
  put 'subscribe', to: 'subscribe#create'
  get 'event' => 'bees#event'
  get 'cards' => 'bees#cards'
  get 'merch' => 'bees#merch'
  get 'cakes' => 'bees#cakes'
  get 'order' => 'bees#order'
  

end

app/models/bee.rb
class Bee < ApplicationRecord

end

app/controllers/bees_controller.rb
class BeesController < ApplicationController
  before_action :set_bee, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /bees
  # GET /bees.json
  def index
  @bees = Bee.all
  @flavor = Flavor.where(flavorofweek:["Yes"]).last
  @lead = Lead.new
  @google_reviews = GoogleReview.all
  set_meta_tags title: "Home",
              site: "B's Ice Cream",
              reverse: true,
              description: "B's Ice Cream serving the best homemade ice cream on the south shore. Come visit our shop in Marshfield, MA for the best homemade ice cream near you.",
              keywords: "best ice cream, homemade ice cream, ice cream, ice cream near me, south shore ice cream, ice cream places near me, ice cream shop, ice cream shops near me, best ice cream near me, ice cream nearby, homemade ice cream near me, ice cream parlour, ice cream stores near me, ice cream parlour near me, creamery near me, the ice cream shop, ice cream around me, nearest ice cream shop, homemade vanilla ice cream, nearest ice cream place, good ice cream near me, closest ice cream, cream ice cream, places to get ice cream near me, ice cream company, best ice cream places near me" 
  end

  def cards
  set_meta_tags title: "Gift Cards",
              site: "B's Ice Cream",
              reverse: true,
              description: "Give the gift of ice cream.  Purchase gift cards online and we will mail them to you. Available in multiple denominations.",
              keywords: "best ice cream, homemade ice cream, ice cream, ice cream near me, south shore ice cream, ice cream places near me, ice cream shop, ice cream shops near me, best ice cream near me, ice cream nearby, homemade ice cream near me, ice cream parlour, ice cream stores near me, ice cream parlour near me, creamery near me, the ice cream shop, ice cream around me, nearest ice cream shop, homemade vanilla ice cream, nearest ice cream place, good ice cream near me, closest ice cream, cream ice cream, places to get ice cream near me, ice cream company, best ice cream places near me" 

  end

  def event
  set_meta_tags title: "Events",
              site: "B's Ice Cream",
              reverse: true,
              description: "Host your next event at B's Ice Cream.  If you're having a party, whether it's a Birthday, Retirement, Anniversary, etc, come celebrate at B’s Ice Cream.",
              keywords: "best ice cream, homemade ice cream, ice cream, ice cream near me, south shore ice cream, ice cream places near me, ice cream shop, ice cream shops near me, best ice cream near me, ice cream nearby, homemade ice cream near me, ice cream parlour, ice cream stores near me, ice cream parlour near me, creamery near me, the ice cream shop, ice cream around me, nearest ice cream shop, homemade vanilla ice cream, nearest ice cream place, good ice cream near me, closest ice cream, cream ice cream, places to get ice cream near me, ice cream company, best ice cream places near me" 

  end

  def merch
  set_meta_tags title: "Merch",
              site: "B's Ice Cream",
              reverse: true,
              description: "Get in Style with B's Ice Cream Merch.  T-Shirts, longsleeve, sweatshirts, and all things B's Ice Cream.",
              keywords: "best ice cream, homemade ice cream, ice cream, ice cream near me, south shore ice cream, ice cream places near me, ice cream shop, ice cream shops near me, best ice cream near me, ice cream nearby, homemade ice cream near me, ice cream parlour, ice cream stores near me, ice cream parlour near me, creamery near me, the ice cream shop, ice cream around me, nearest ice cream shop, homemade vanilla ice cream, nearest ice cream place, good ice cream near me, closest ice cream, cream ice cream, places to get ice cream near me, ice cream company, best ice cream places near me" 

  end

  # GET /bees/1
  # GET /bees/1.json
  def show
  end

  def about
  set_meta_tags title: "About",
              site: "B's Ice Cream",
              reverse: true,
              description: "Family owned ice cream shop making all homemade flavors on site daily",
              keywords: "best ice cream, homemade ice cream, ice cream, ice cream near me, south shore ice cream, ice cream places near me, ice cream shop, ice cream shops near me, best ice cream near me, ice cream nearby, homemade ice cream near me, ice cream parlour, ice cream stores near me, ice cream parlour near me, creamery near me, the ice cream shop, ice cream around me, nearest ice cream shop, homemade vanilla ice cream, nearest ice cream place, good ice cream near me, closest ice cream, cream ice cream, places to get ice cream near me, ice cream company, best ice cream places near me" 

  end

  def order
  set_meta_tags title: "Order Online",
              site: "B's Ice Cream",
              reverse: true,
              description: "Order online from all B's Ice Cream locations online",
              keywords: "best ice cream, homemade ice cream, ice cream, ice cream near me, south shore ice cream, ice cream places near me, ice cream shop, ice cream shops near me, best ice cream near me, ice cream nearby, homemade ice cream near me, ice cream parlour, ice cream stores near me, ice cream parlour near me, creamery near me, the ice cream shop, ice cream around me, nearest ice cream shop, homemade vanilla ice cream, nearest ice cream place, good ice cream near me, closest ice cream, cream ice cream, places to get ice cream near me, ice cream company, best ice cream places near me" 

  end

  # GET /bees/new
  def new
    @bee = Bee.new
  end

  # GET /bees/1/edit
  def edit
  end

  # POST /bees
  # POST /bees.json
  def create
    @bee = Bee.new(bee_params)

    respond_to do |format|
      if @bee.save
        format.html { redirect_to @bee, notice: 'Bee was successfully created.' }
        format.json { render :show, status: :created, location: @bee }
      else
        format.html { render :new }
        format.json { render json: @bee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bees/1
  # PATCH/PUT /bees/1.json
  def update
    respond_to do |format|
      if @bee.update(bee_params)
        format.html { redirect_to @bee, notice: 'Bee was successfully updated.' }
        format.json { render :show, status: :ok, location: @bee }
      else
        format.html { render :edit }
        format.json { render json: @bee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bees/1
  # DELETE /bees/1.json
  def destroy
    @bee.destroy
    respond_to do |format|
      format.html { redirect_to bees_url, notice: 'Bee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bee
      @bee = Bee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bee_params
      params.fetch(:bee, {})
    end

end

app/helpers/bees_helper.rb
module BeesHelper
end

app/views/bees/_form.html.erb
<%= form_for(@bee) do |f| %>
  <% if @bee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bee.errors.count, "error") %> prohibited this bee from being saved:</h2>

      <ul>
      <% @bee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bees/_testimonials.html.erb
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <% reviews.each_with_index do |review, index| %>
      <% active_class = index == 0 ? 'active' : '' %>
      <div class="carousel-item <%= active_class %>">
        <blockquote class="blockquote text-center">
          <p class="mb-0">
            <i class="fa fa-quote-left"></i>
            <%= review.text %>
          </p>
          <footer class="blockquote-footer mt-2">
            <img class="rounded-circle shadow-1-strong mb-4"
                src=<%= review.profile_photo_url %> alt="avatar"
                style="width: 150px;" />
            <div><%= review.author_name %></div>
          </footer>
          <p class="client-review-stars">
            <% review.rating.times do %>
              <i class="fas fa-star"></i>
            <% end %>
            <% (5 - review.rating).times do %>
              <i class="far fa-star"></i>
            <% end %>
          </p>
        </blockquote>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/bees/about.html.erb
<!-- hero -->
<div class="dzsparallaxer auto-init height-is-based-on-content "  data-options='{   direction: "reverse"}'>
    <div class="divimage dzsparallaxer--target " style="width: 101%; height: 130%; background-image: url(<%= image_path('cones-smaller.jpg')%>)">
    </div>
    <div class="container pt100 pb70">
        <div class="row pb50">
            <div class="col-md-8 ml-auto mr-auto wow bounceIn" data-wow-delay=".2s">
                <h3 class="h1 text-center font300  pt100 text-white">About - Us</h3>
            </div>
        </div>
    </div>
</div><!--parallax-->
<!--/.page-title-->

<!-- About us main-->
<div class="container pt90 pb60">
  <div class="row mb50">
    <div class="col-md-8 mr-auto ml-auto text-center">
      <h2 class="mb30">B's Ice Cream</h2>
      <p class="lead">
       Hi! We’re B’s Ice Cream, a family run business, based in Marshfield, MA. Our lifelong ambition was to own and operate a homemade ice cream shop. In 2018 after working in a corporate environment for many years we decided the time was now! We launched B's in 2019 with the goal of providing premium homemade ice cream to the south shore. We make our ice cream in-house with the freshest ingredients possible and hope you’ll enjoy traditional favorites along with our unique flavors.

      </p>
    </div>  
  </div><!--row-->
</div> <!-- about us main -->

<!-- about us container -->
<div class='container pt10 pb10'>
  <div class='row'>
      <!-- flavors box -->
      <div class="col-lg-6 mb50">
        <a class="shop-item-card" href="/#visit_us">
          <div class="card-image">
            <img src="<%= image_path('deck.jpg')%>" alt="" class="img-fluid"> 
              <h5>Location</h5>
              <h6>
              We’re located at 57 Snow Rd. Marshfield, MA in the Webster Square shopping center. Come visit us for some homemade dessert after visiting one of the many shops and restaurants in the area.
              </h6>
          </div>
        </a>
      </div> <!-- flavors box -->
      <!-- order online box -->
      <div class="col-lg-6 mb50">
        <a class="shop-item-card" href="">
          <div class="card-image">
            <img src="<%= image_path('bucket.png')%>" alt="" class="img-fluid">
            <h5>What we do</h5>
            <h6>
              We make all our ice cream in-house! We love classic flavors as well as unique flavors that you haven’t tried before. We have seasonal specials and limited flavors that rotate throughout the year. We strive to use the freshest ingredients such as fruit that’s local and in season. We’re always sourcing the best quality and best tasting ingredients for our ice cream. Sometimes the best tasting ingredients are Oreos, and sometimes it’s pure vanilla from Madagascar.
            </h6>   
          </div>
        </a>
      </div> <!-- end order online box -->
      <!-- flavors box -->
  </div>
</div> <!-- about us container -->

<div class='bg-dark pt90 pb90'>
    <div class='container'>
        <div class='row'>
            <div class='col-md-8 mr-auto ml-auto text-center'>
                <h3 class='text-white h2'>
                    We're always looking for talent
                </h3>
                <p class='lead text-white text-muted'>
                    If you are interested in joining the team please contact us to learn about job opportunities. 
                </p>
                <a href="mailto:bshomemadeic@gmail.com"  class='btn btn-light btn-lg btn-rounded'>Contact Us</a>
            </div>
        </div>
    </div>
</div>

app/views/bees/cakes.html.erb
<div class="bg-dark pt90 pb30">
</div>  

<div class='saas-app-hero bg-faded'>
  <div class='container pt30 pb10'>
    <div class='row align-items-center'>
      <div class='col-md-12'>
          <h1 class=' h1 mb20 text-center font500'>B's Ice Cream Cakes</h1>
        </div>
      </div>
    </div>
  </div>
</div> 


<div class="bg-faded pt90">
    <div class="container">
        <div class='feature-col saas-features pb90'>
            <div class='row align-items-center'>

                <div class='col-lg-5 mr-auto'>

                <h2 class="font350 h1">All cakes made to order</h2>
                <p class="lead">
                We are now providing ice cream cakes in 18" and 21" sizes  
                </p>
                <ul>
                 <li>We need 48 hours from the time of your order</li> 
                 <li>Flavor options will include what is in store at the time of order</li>
                 <li>18" Cake - $31.99</li>
                 <li>24" Cake - $38.99</li>
                </ul>    
                <p>Call us today to place your order
                    <span class="bg-faded"><a href="tel:+17819224062" class="btn btn-underline text-black">Phone: (781) 922-4062</a>
                    </span>
                </p>
                <p>Email Us 
                    <span class="bg-faded">
                    <a href="mailto:bshomemadeic@gmail.com" class="btn btn-underline text-black">
                        bshomemadeic@gmail.com
                    </a>
                    </span>
                </p>
   
                </div>
                <div class='col-lg-6 pt50-md'>
                    <img src='<%= image_path('cake.jpg')%>' alt='' class='img-fluid'>
                </div>
            </div>
        </div><!--feature col-->
    </div>
</div>

app/views/bees/cards.html.erb
<div class="bg-dark pt90 pb30">
</div>

<div class='saas-app-hero bg-faded'>
  <div class='container pt30 pb10'>
    <div class='row align-items-center'>
      <div class='col-md-12'>
          <h2 class=' h1 mb20 text-center font500'>
              Order B's Ice Cream Gifts Cards Online
          </h2>
          <p class='lead text-muted text-center mb40'>
              Will mail to you via USPS witin 2 business days. If you need same day please purchase in our shop during business hours.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>   

<div class='container pt30 pb30' style="align-items: center !important;">
  <div class='row align-items-center'>  
    <div class='col-md-4'></div>
    <div class='col-md-4'>
      <div id='product-component-3b5ecbdd676'>
      </div>
    <div class='col-md-4'></div>
  </div>
</div>

<br>

<script type="text/javascript">
  /*<![CDATA[*/

  (function () {
  var scriptURL = 'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js';
  if (window.ShopifyBuy) {
    if (window.ShopifyBuy.UI) {
      ShopifyBuyInit();
    } else {
      loadScript();
    }
  } else {
    loadScript();
  }

  function loadScript() {
    var script = document.createElement('script');
    script.async = true;
    script.src = scriptURL;
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(script);
    script.onload = ShopifyBuyInit;
  }

  function ShopifyBuyInit() {
    var client = ShopifyBuy.buildClient({
      domain: 'bs-homemade-ice-cream.myshopify.com',
      storefrontAccessToken: '8b10f80e2b9c9be7315b96f4797e42e9',
    });

    ShopifyBuy.UI.onReady(client).then(function (ui) {
      ui.createComponent('product', {
        id: [1327986212911],
        node: document.getElementById('product-component-3b5ecbdd676'),
        moneyFormat: '%24%7B%7Bamount%7D%7D',
        options: {
          "product": {
          "variantId": "all",
          "contents": {
          "imgWithCarousel": false,
          "variantTitle": false,
          "description": false,
          "buttonWithQuantity": false,
          "quantity": false
          },
          "styles": {
          "product": {
            "@media (min-width: 601px)": {
              "max-width": "calc(25% - 20px)",
              "margin-left": "20px",
              "margin-bottom": "50px"
            }
          }
          }
          },
          "cart": {
          "contents": {
          "button": true
          },
          "styles": {
          "footer": {
            "background-color": "#ffffff"
          }
          }
          },
          "modalProduct": {
          "contents": {
          "img": false,
          "imgWithCarousel": true,
          "variantTitle": false,
          "buttonWithQuantity": true,
          "button": false,
          "quantity": false
          },
          "styles": {
          "product": {
            "@media (min-width: 601px)": {
              "max-width": "100%",
              "margin-left": "0px",
              "margin-bottom": "0px"
            }
          }
          }
          },
          "productSet": {
          "styles": {
          "products": {
            "@media (min-width: 601px)": {
              "margin-left": "-20px"
            }
          }
          }
          }
          }
      });
    });
  }
  })();
  /*]]>*/
</script>

app/views/bees/edit.html.erb
<h1>Editing Bee</h1>

<%= render 'form' %>

<%= link_to 'Show', @bee %> |
<%= link_to 'Back', bees_path %>

app/views/bees/event.html.erb
<div class="bg-dark pt90 pb30">
</div>   

<div class='saas-app-hero bg-faded'>
  <div class='container pt50 pb30'>
    <div class='row align-items-center'>
      <div class='col-md-12'>
          <h2 class=' h1 mb20 text-center font500'>
              Host your next event at B's Ice Cream
          </h2>
          <p class='h5 text-center mb40'>
              If you're having a party, whether it's a Birthday, Retirement, Anniversary, etc, come celebrate at B’s Ice Cream.
          </p>
      </div>
    </div>
  </div>
</div>


<!-- host your event section -->
<div class="bg-faded pt40">
    <div class="container">
        <div class='feature-col saas-features pb90'>
            <div class='row align-items-center'>

                <div class='col-lg-5 mr-auto'>

                <h2 class="font350 h1">Host Your Event</h2>
                <p class="lead">
                Host your event or fundraiser at B's Icecream   
                </p>
                <p class="lead">
                 <strong> Events:</strong>  
                </p>
                <p>
                 Staff appreciation, catch up with friends, kids sundae party, retirement, a place to bring clients
                </p>
                <p class="lead">
                <strong>Fundraiser:  </strong>
                </p>
                 <p>
                 Have a great cause that needs a boost or an organization that needs to raise funds for an upcoming event? You can raise funds with B’s Ice Cream. We’ll donate a portion of all sales to your organization, cause or school.
                </p>
                  
               <!--  <p>Call us today to book 
                    <span class="bg-faded"><a href="tel:+17819224062" class="btn btn-underline text-black">Phone: (781) 922-4062</a>
                    </span>
                </p>
                <p>Email Us 
                    <span class="bg-faded">
                    <a href="mailto:bshomemadeic@gmail.com" class="btn btn-underline text-black">
                        bshomemadeic@gmail.com
                    </a>
                    </span>
                </p>
                <p>*** Call today to reserve date and time ***
                </p> -->
   
                </div>
                <div class='col-lg-6 pt50-md'>
                    <img src='<%= image_path('privateevents.JPG')%>' alt='' class='img-fluid'>
                </div>
            </div>
        </div><!--feature col-->
    </div>
</div> <!-- end host your event section -->



<!-- bday party section -->
<div class="bg-white pt40">
    <div class="container">
        <div class='feature-col saas-features pb90'>
            <!-- row 1 -->
            <div class='row align-items-center'>
                <div class='col-lg-6 pt50-md'>
                  <img src='<%= image_path('bdayparty.jpg')%>' alt='' class='img-fluid'>
                </div>                
                
                <!-- private kids party -->
                <div class="col-lg-5 ml-auto pt40 pb40">
                    <h2 class="font350 h3">Kid’s Ice Cream Party</h2>
                    <p class="lead">
                    Thursday thru Sunday 10:30am – 12pm<br>
                    Maximum of 15 children and 4 adult chaperones.
                    </p>
                    <ul>
                     <li>Each Child will receive a kid’s specialty sundae – Dirt Sundae or Unicorn Sundae (number of each needed 2 days prior to event)</li> 
                     <li>depending on age they can make their own sundaes (guest to decide)</li>
                     <li>Kids Music, napkins, utensils and paper plates provided</li>
                     <li>Drink for each child and 1 slice of pizza for each child</li>
                     <li>Dedicated party host</li>    
                     <li>We do all the set up and clean up</li> 
                     <li>Party Starts promptly at 10:30 am</li>
                    </ul> 
                    Children ages 1 and up are included in your total<br>
                    <strong>SORRY, NO OUTSIDE FOOD OR DRINK PRODUCTS ALLOWED</strong><br>
                    
                    </p>   
                </div> <!-- end private kids party -->

            </div>
            <!-- end row 1-->  
            <!-- row 2 -->
            <div class='row align-items-center'>  
                <!-- disclaimers -->
                
                <!-- Host your next party -->
                <div class='col-lg-6 pt50-md'>
                  <img src='<%= image_path('bdayparty2.jpg')%>' alt='' class='img-fluid'>
                </div>   <!-- host next party end -->
                
                <!-- non private kids party -->
                <div class="col-lg-5 ml-auto pt40 pb40">
                    <h2 class="font350 h3">Ice Cream Social</h2>
                    <p class="lead">
                    Monday thru Friday 3pm – 7pm<br>
                    Maximum of 10 children and 2 adult chaperones.
                    </p>
                    <ul>
                     <li>Each Child will receive a kid’s specialty sundae – Dirt Sundae or Unicorn Sundae (number of each needed 2 days prior to event)</li> 
                     <li>depending on age they can make their own sundaes (guest to decide)</li>
                     <li>Reserved tables for the party guests.</li>
                    </ul> 
                    Children ages 1 and up are included in your total<br>
                    <strong>SORRY, NO OUTSIDE FOOD OR DRINK PRODUCTS ALLOWED</strong><br>   
                </div> <!-- end non private kids party -->
            </div>  <!-- end row 2 --> 

            <!-- button row -->
            <div class='row text-center'>  
              <div class='col-lg-12 pt50-md'>
                <!-- contact us -->
                <p class='h5 text-center mb10'>
                  * Deposit required to reserve date<br>
               <!--    * Prices are subject to change <br>  -->
                </p>
                <p class='h5 text-center mb10'>Contact us today to book</p> 

                <!-- end contact us -->
                <a class='btn btn-xl btn-secondary btn-rounded' href="tel:+17819224062">
                  Call (781) 922-4062
                </a>
                <a class='btn btn-xl btn-primary btn-rounded' href="mailto:bshomemadeic@gmail.com">
                  Email bshomemadeic@gmail.com
                </a>
              </div>    


           </div> <!-- end button row -->
        </div>       
    </div>
</div>

app/views/bees/new.html.erb
<h1>New Bee</h1>

<%= render 'form' %>

<%= link_to 'Back', bees_path %>

app/views/bees/order.html.erb
<body>
  <!--page title-->
<div class="dzsparallaxer auto-init height-is-based-on-content "  data-options='{   direction: "reverse"}'
data-responsive-reference-width="1280" 
data-responsive-optimal-height="500"
  >
	<div class="divimage dzsparallaxer--target" style="width: 100%; height: 100%; background-image: url(<%= image_path('order.jpg')%>)">
	</div>
			<div class="container pt100 pb70">
				<div class="row pb50">
		  		<div class="col-md-8 ml-auto mr-auto wow bounceIn" data-wow-delay=".2s">
		    		<h3 class="h1 text-center font500  pt100 text-black"></h3>
		     	</div>
		   	</div>
			</div>
	 	</div><!--parallax-->
	  <!--/.page-title-->

 
  <!-- Title Header -->
<div class="bg-light pt40 pb40">
	  <div class="col-md-8 mr-auto ml-auto text-center">
	  	<h3 class="mb0 h1">
	          Order Online
	    </h3>
	    <p>Pre-order for Same Day pickup at each of our locations</p>
	 	</div>
</div>	

        
 <!-- location panel -->
 <div class="row">
        <!-- Marshfield section -->
        <div class="col-md-4 mb40">
             <h3 class="mb40 h1">Marshfield</h3>
				<!-- Image              -->
      <div class="col-lg-10">
          <div class="card-image">
          	<a class="shop-item-card" href="https://bs-ice-cream.square.site">
            		<img src="<%= image_path('marshfield.jpg')%>" alt="" class="img-fluid">
        		</a>
          </div>
      </div> <!-- end order online box -->
      <!-- address -->
        <div class="media mb20">
            <span class="icon-round-40 mr-3 bg-light"><i class="fa fa-home"></i></span>
            <p class="media-body pt5 text-white">
              <a href="https://goo.gl/maps/QAZGAwyZVtMb2k1z8" target="_blank">
                57 Snow Road,
                Marshfield, MA
                02050
            </p>
          </a>
        <!-- phone -->
        </div>
            <div class="media mb20">
                <span class="icon-round-40 float-left mr-3 bg-light"><i class="fa fa-phone"></i></span>
                <p class="media-body pt5">
                    <a href="tel:+17819224062">Phone: (781) 922-4062</a></p>
            </div>
            <a class="btn btn-outline-secondary btn-xl btn-rounded" href="https://bs-ice-cream.square.site"> Order from Marshfield</a>
        </div>

        <!-- Kingston section -->
        <div class="col-md-4 mb40">
             <h3 class="mb40 h1">Kingston</h3>
				<!-- Image              -->
       <div class="col-lg-10">
          <div class="card-image">
          	<a class="shop-item-card" href="https://bs-ice-cream-kingston.square.site">
            		<img src="<%= image_path('kingston.jpg')%>" alt="" class="img-fluid">
        		</a>
          </div>
      </div> <!-- end order online box -->
            <div class="media mb20">
                <span class="icon-round-40 mr-3 bg-light"><i class="fa fa-home"></i></span>
                <p class="media-body pt5">
                  <a href="https://www.google.com/maps/place/B's+Ice+Cream/@42.0086064,-70.7321996,15z/data=!4m6!3m5!1s0x89e4a3c65d132a53:0x81c2608062cb9326!8m2!3d42.0086064!4d-70.7321996!16s%2Fg%2F11tw_2m6yg" target="_blank">
                    164 Summer St
                    Kingston, MA
                    02364
                </p>
              </a>
            </div>

            <div class="media mb20">
                <span class="icon-round-40 float-left mr-3 bg-light"><i class="fa fa-phone"></i></span>
                <p class="media-body pt5">
                    <a href="tel:+17813617084">Phone: (781) 361-7084</a></p>
            </div>
        <a class="btn btn-outline-secondary btn-xl btn-rounded" href="https://bs-ice-cream-kingston.square.site/"> Order from Kingston</a>
        </div>

            <!-- Plymouth section -->
        <div class="col-md-4 mb40">
             <h3 class="mb40 h1">Plymouth</h3>
                <!-- Image              -->
       <div class="col-lg-10">
          <div class="card-image">
            <a class="shop-item-card" href="https://bs-ice-cream-plymouth.square.site">
                    <img src="<%= image_path('plymouthorder.jpg')%>" alt="" class="img-fluid">
                </a>
          </div>
      </div> <!-- end order online box -->
            <div class="media mb20">
                <span class="icon-round-40 mr-3 bg-light"><i class="fa fa-home"></i></span>
                <p class="media-body pt5">
                  <a href="https://www.google.com/maps/place/B's+Ice+Cream/@41.9618571,-70.6692452,15z/data=!4m6!3m5!1s0x89e4bb4d47828b35:0x4629da531d02eb66!8m2!3d41.9618571!4d-70.6692452!16s%2Fg%2F11y1l3742q?entry=ttu" target="_blank">
                    170 Water St
                    Plymouth, MA
                    02360
                </p>
              </a>
            </div>

            <div class="media mb20">
                <span class="icon-round-40 float-left mr-3 bg-light"><i class="fa fa-phone"></i></span>
                <p class="media-body pt5">
                    <a href="tel:+15089271254">Phone: (508) 927-1254</a></p>
            </div>
        <a class="btn btn-outline-secondary btn-xl btn-rounded" href="https://bs-ice-cream-plymouth.square.site/"> Order from Plymouth</a>
        </div>
    </div>
</div>


</body>

app/views/bees/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bee_path(@bee) %> |
<%= link_to 'Back', bees_path %>