config/routes.rb
Rails.application.routes.draw do

  devise_for :users,  :controllers => { :users => 'users' }
  devise_for :models
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'bees#index'

  resources :posts
  resources :flavors
  resources :bees
  resources :admin_users
  resources :leads
  resources :faqs, only: %i[index]
  resources :job_applicants, only: %i[new create]
  resources :trailers, only: %i[new create]

  namespace :admin do
    resources :google_reviews do
      post :upsert_reviews, on: :collection
    end
  end

  get 'about' => 'bees#about'
  put 'subscribe', to: 'subscribe#create'
  get 'event' => 'bees#event'
  get 'cards' => 'bees#cards'
  get 'merch' => 'bees#merch'
  get 'cakes' => 'bees#cakes'
  get 'order' => 'bees#order'
  

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bee.rb
class Bee < ApplicationRecord

end

app/models/faq.rb
class Faq < ApplicationRecord
  include RichTextToPlainText

  validates :question, presence: true

  has_rich_text :answer

  acts_as_list

  after_commit :update_faq_schema

  private

  def update_faq_schema
    Rails.cache.delete('faq_schema')

    Rails.cache.fetch('faq_schema') do
      FaqSchemaGenerator.new.generate_schema(Faq.order(position: :asc))
    end
  end
end

app/models/flavor.rb
class Flavor < ApplicationRecord
  belongs_to :bee, optional: true
  mount_uploader :image, ImageUploader

  def self.descriptions
    pluck(:description).flatten.join(' ')
  end

  def self.names
    pluck(:name).flatten.join(' ')
  end

  def self.images
    pluck(:image).flatten.join(' ')
  end

  def self.search(search)
    if search
      self.where("title LIKE ? OR body LIKE ?", "%#{search}%", "%#{search}%")
    else
      self.all
    end
  end
end

app/models/google_review.rb
class GoogleReview < ApplicationRecord
end

app/models/job_applicant.rb
class JobApplicant < ApplicationRecord
  validates :first_name, :last_name, :phone_number, :work_location, :position, :start_at,
            :unavailability_reason, :high_school_attendee_year, :college_attendee_year, :job_history,
            :valid_age_range_work_permit, :fav_icecream_flavor, :referee_referrer_name, presence: true

  validates :email, presence: true, uniqueness: true
  validates :hours_available, presence: true, numericality: { in: 1..80, message: "must be in valid range" }
  validate :start_at_not_in_past
  
  after_create :send_email_notifications
  
  # Send email notifications to admin and applicant after successful creation
  def send_email_notifications
    # Notify admin
    JobApplicantMailer.with(
      applicant_email: email,
      applicant_name: first_name,
      selected_position: position
    ).notify_admin.deliver_later
    
    # Notify applicant
    JobApplicantMailer.with(
      applicant_email: email,
      applicant_name: first_name
    ).notify_applicant.deliver_later
  end

  private

  def start_at_not_in_past
    if start_at.present? && start_at < Date.current
      errors.add(:start_at, "must be on or after today's date")
    end
  end
end

app/models/lead.rb
class Lead < ApplicationRecord
validates :fname, :lname, :email, presence: true

after_create :subscribe_user_to_list

  def subscribe_user_to_list
    gibbon = Gibbon::Request.new(api_key: Rails.application.credentials.mailchimp_api_key, debug: true)
    begin
      gibbon.lists(Rails.application.credentials.mailchimp_list_id).members.create(body: {
        email_address: self.email,
        status: "subscribed",
        merge_fields: {:FNAME => self.fname, :LNAME => self.lname}
      })
    rescue Gibbon::MailChimpError => error
      GithubIssues.create(error, self.class.name, __method__, self.inspect)
    end
  end

end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  paginates_per 5
  ATTACHMENT_NAMES_REGEX = /\[(.*?)\]/

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_rich_text :description

  def content_to_plain_text
    plain_text_content = description.to_plain_text

    return unless plain_text_content.present?

    plain_text_content.gsub(ATTACHMENT_NAMES_REGEX, '')
  end
end

app/models/trailer.rb
class Trailer < ApplicationRecord
  validates :firstname, :lastname, :detail, :email, :phone, :date, :address1, :city, :state, :zip, :eventstart, :guest, presence: true
  
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }
  validates :guest, numericality: { greater_than: 0, message: "must be a positive number" }
  validates :zip, format: { with: /\A\d{5}(-\d{4})?\z/, message: "should be a valid ZIP code (e.g., 12345 or 12345-6789)" }, allow_blank: true
  
  validate :date_not_in_past
  validate :date_not_too_far_in_future

  after_create_commit :send_emails

  private

  def date_not_in_past
    if date.present? && date < Date.current
      errors.add(:date, "must be on or after today's date")
    end
  end
  
  def date_not_too_far_in_future
    if date.present? && date > Date.current + 2.years
      errors.add(:date, "cannot be more than 2 years in the future")
    end
  end

  def send_emails
    # Send notification email to shop owners
    TrailerMailer.notify_shop(self).deliver_later
    
    # Send acknowledgment email to the customer
    TrailerMailer.acknowledgment(self).deliver_later
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :bees
  after_create :subscribe_user_to_list

  def subscribe_user_to_list
    gibbon = Gibbon::Request.new(api_key: Rails.application.credentials.mailchimp_api_key, debug: true)
    begin
      gibbon.lists(Rails.application.credentials.mailchimp_list_id).members.create(body: {
        email_address: self.email,
        status: "subscribed",
        merge_fields: {:FNAME => self.fname, :LNAME => self.lname}
      })
    rescue Gibbon::MailChimpError => error
      GithubIssues.create(error, self.class.name, __method__, self.inspect)
    end
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bees_helper.rb
module BeesHelper
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscribe_helper.rb
module SubscribeHelper
end

app/helpers/trailers_helper.rb
module TrailersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 350, 350 ] : [ 350, 350 ]), class: 'img-fluid' %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
	>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
	<%= favicon_link_tag 'favicon.png' %>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-129290811-1"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-129290811-1');
	</script>
	<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<script>
	     (adsbygoogle = window.adsbygoogle || []).push({
	          google_ad_client: "ca-pub-5519376602594387",
	          enable_page_level_ads: true
	     });
	</script>
	<script src="https://cdn.jsdelivr.net/gh/cferdinandi/smooth-scroll@15.0.0/dist/smooth-scroll.polyfills.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js" integrity="sha512-Eak/29OTpb36LLo2r47IpVzPBLXnAMPAVypbSZiZ4Qkf8p/7S/XRG5xp7OKWPPYfJT6metI+IORkR5G8F900+g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://www.google.com/recaptcha/api.js?render=<%= Rails.application.credentials.recaptcha_site_key_v3 %>"></script>

	<%= display_meta_tags %>
	<%= stylesheet_link_tag 'application', media: 'all', "data-turbo-track": "reload" %>
  <%= javascript_include_tag 'application', "data-turbo-track": "reload", defer: true %>
</head>
<body>
	<!-- nabar -->
	<nav class="navbar navbar-expand-lg navbar-light navbar-transparent navbar-sticky">
		<!-- logo icon header -->
			<%= link_to root_path do %>
				<img src="<%= image_path('webfontdark.svg')%>" alt="" class="logo-visible-desktop logo-default" style="width: 100 px; Height: 50px; text-align: left;">
				<img src="<%= image_path('webfontdark.svg')%>" alt="" class="logo-hidden-desktop logo-scroll" style="width: 100 px; Height: 50px; text-align: left;">
			<% end %>

			<!-- navbar toggle -->
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>


		<!-- navbar menu -->
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav ml-auto">
				<!-- homepage link -->
				<li class="nav-item">
					<a>
						<%= link_to "Home", bees_path, class: 'nav-link', style:'font-size: .85rem important!;', data: { turbo_frame: '_top' }%>
					</a>
				</li>
				<!-- info link -->
				<li class="nav-item">
					<a>
						<%= link_to "Info", "/#visit_us",class: 'nav-link', data: { turbo_frame: '_top' } %>
					</a>
				</li>
				<!-- flavors link -->
				<li class="nav-item">
					<a>
						<%= link_to "Flavors", flavors_path, class: 'nav-link', data: { turbo_frame: '_top' } %>
					</a>
				</li>
				<!-- order now link -->
				<li class="nav-item">
					<a>
						<%= link_to "Order Now", order_path, class: 'nav-link' %>
					</a>
				</li>
				<!-- Truck link		                 -->
				<li class="nav-item">
					<a>
						<%= link_to "Ice Cream Truck", new_trailer_path, class: 'nav-link', data: { turbo_frame: '_top' } %>
					</a>
				</li>				<!-- blog link		                 -->
				<li class="nav-item">
					<a>
						<%= link_to "B's Updates", posts_path, class: 'nav-link', data: { turbo_frame: '_top' } %>
					</a>
				</li>
				<!-- Hiring form link -->
				<li class="nav-item">
					<%= link_to "B's Hiring", new_job_applicant_path, class: 'nav-link', data: { turbo_frame: '_top' } %>
				</li>
				<!-- FAQS link -->
				<li class="nav-item">
					<%= link_to "FAQ'S", faqs_path, class: 'nav-link', data: { turbo_frame: '_top' } %>
				</li>
				<!-- gift cards link -->
<!-- 		            <li class="nav-item">
					<a>
						<%#= link_to "Gift Cards", cards_path, class: 'nav-link', 'data-turbolinks' => false %>
					</a>
				</li>		 -->
				<!-- events link -->
				<!-- <li class="nav-item"> -->
					<!-- <a> -->
						<%#= link_to "Events", event_path, class: 'nav-link', 'data-turbolinks' => false %>
					<!-- </a> -->
				<!-- </li>			                     -->
				<!-- merch link -->
				<!-- <li class="nav-item"> -->
					<!-- <a> -->
						<%#= link_to "Merch", merch_path, class: 'nav-link', 'data-turbolinks' => false %>
						<!-- </a> -->
				<!-- </li>	 -->
				<!-- about us link -->
				<!-- <li class="nav-item"> -->
					<!-- <a> -->
						<%#= link_to "About", about_path, class: 'nav-link', 'data-turbolinks' => false %>
					<!-- </a> -->
				<!-- </li>		 -->
			</ul>
		</div>

		<!-- right nav bar social icons-->
			<div class="navbar-right-col">
				<div class="container">
					<div class="row">
						<ul class="social list-inline mb30">
								<li class="list-inline-item"><a class="facebook" href="https://www.facebook.com/Bs-Homemade-Ice-Cream-144977852873757" target="_blank"><i class="fa-brands fa-facebook-f" style="color: white"></i></a></li>
								<li class="list-inline-item"><a class="instagram" href="https://www.instagram.com/bshomemadeic" style="color: white" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
	</nav>

	<%= yield %>
  <!-- footer -->

  <footer class="footer">
      <div class="container">


          <div class="row">
          	<!-- what we do column -->
              <div class="col-md-6 col-lg-3">
                  <h4>B's Homemade</h4>
                  <p>
                      We make a variety of flavors on location daily.  Come visit us to experience the best homemade ice cream on the south shore. 
                  </p>
              </div><!--/.column-->
              <!-- contact us column -->
              <div class="col-md-6 col-lg-3">
                  <h4>Contact Us</h4>
                  <ul class="list-unstyled">
                      <li><a href="mailto:bshomemadeic@gmail.com" class="btn btn-underline">Email: bshomemadeic@gmail.com</a></li>
                      
                  </ul>

              </div><!--/.column-->
              <div class="col-md-6 col-lg-3">
                  <h4>Links</h4>
                  <ul class="list-unstyled">
                      <li>
                      	<a>
		                  		<%= link_to "Info", "/#visit_us",class: 'btn btn-underline', data: { turbo_frame: '_top' } %>
		                  	</a>
		                	</li>
		                	<li>
                      	<a>
		                  		<%= link_to "Flavors", flavors_path, class: 'btn btn-underline', data: { turbo_frame: '_top' } %>
		                  	</a>
		                	</li>
		                	<li>
                      	<a>
		                  		<%= link_to "What's New", "/#whats_new", class: 'btn btn-underline', data: { turbo_frame: '_top' } %>
		                  	</a>
		                	</li>
		                	<li>
                      	<a>
		                  		<%= link_to "Blog", posts_path, class: 'btn btn-underline', data: { turbo_frame: '_top' } %>
		                  	</a>
		                	</li>
		                	<li>
                      	<a>
		                  		<%= link_to "Hiring", new_job_applicant_path, class: 'btn btn-underline', data: { turbo_frame: '_top' } %>
		                  	</a>
		                	</li>
                      	<a>
		                  		<%= link_to "About Us", about_path, class: 'btn btn-underline', data: { turbo_frame: '_top' } %>
		                  	</a>
		                	</li>
                  </ul>
              </div><!--/.column-->
              <!-- right column -->
              <div class="col-md-6 col-lg-3">
                  <h4>Connect with Us</h4>
                  <div class="mb30">
                      <form>
                      	
                          <div class="form-group">
                          <%#= form_for @lead do |f| %>
                              <label for="subscribe">Check us out on social media</label>

                              <%#= f.email_field :email, placeholder: "  Email", class: "form-control"%>
                              <br>
                              <%#= f.submit "Join Newsletter", class: 'btn btn-outline-secondary btn-sm' %>
                          </div>
                          <%# end %>
                      </form>
                  </div>
						        <ul class="social list-inline mb30">
						            <li class="list-inline-item"><a class="facebook" href="https://www.facebook.com/Bs-Homemade-Ice-Cream-144977852873757" target="_blank"><i class="fa-brands fa-facebook-f" style="color: white"></i></a></li>
						            <li class="list-inline-item"><a class="instagram" href="https://www.instagram.com/bshomemadeic" style="color: white" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
						        </ul>
                  <span class="font400">&copy; B's Homemade LLC 2018</span>
              </div><!--/.column-->
          </div><!--/.row-->
      </div><!--/.container-->
  </footer>
<script id="dsq-count-scr" src="//bs-ice-cream.disqus.com/count.js" async></script>
</body>
</html>

app/views/layouts/flash_messages/_html_toastr.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <%= render 'layouts/flash_messages/toastr_flash' %>
  </script>
<% end %>

app/views/layouts/flash_messages/_toastr_flash.html.erb
<% flash.each do |f| %>
  <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'success') %>
  toastr['<%= type %>'](
    '<%= f[1] %>', '', {
    "closeButton": true,
    "showDuration": "300",
    "hideDuration": "1000",
    "timeOut": "5000",
    "extendedTimeOut": "1000",
    "showEasing": "swing",
    "hideEasing": "linear",
    "showMethod": "fadeIn",
    "progressBar": true,
    "hideMethod": "fadeOut"
  });
<% end %>